framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            node_modules/gasparesganga-jquery-loading-overlay/dist/: 'jquery-loading'
            node_modules/bootstrap/dist/: 'bootstrap'
            node_modules/jquery/dist/: 'jquery'
            assets/: ''
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
